### PR TITLE
added analytics integration with Piwik using angulartics module

### LINKED ISSUE #58: Add Piwik Tracking
At least during development detailed analytics on how the app is used are helpful. We can use [Piwik](http://piwik.org/) (OSS alternative to Google Analytics) for this.

AngularJS Integration is available through https://github.com/angulartics/angulartics

### PR DESCRIPTION
**Pull request by sebastian-leidig**
closes #58

### CODE REVIEW

**Comment by fschoell** [comment]
I think we should test this with an actual Piwik backend. Do you have a webserver to test this?

**Comment by sebastian-leidig** [comment]
@fschoell Of course you're right. I did test it and sent you access to the piwik instance now by email. Check it out.

**Comment by fschoell** [comment]
Ok, somehow I can't see my visits on Piwik. I enabled piwik in the app-config, changed the url and the site id. The Piwik call responds with 204 (which is good), but the Piwik dashboard doesn't show any visits for today. Maybe this is due to some misconfiguration or because the domain is localhost (even though I have explicitly added localhost as site domain in the Piwik settings). 

Code looks good however (fits the tracking code from the Piwik Dashboard) and the Piwik requests are made and successfully responded. So I'm going to merge and close this. The problems are most probably due to configuration and therefore site specific.

**Comment by fschoell** [comment]
Okay, the Piwik FAQ states that localhost urls are not tracked.

**Pull request merged**
